### ISSUE TITLE
What about native DLLs?

### ISSUE THREAD

**Issue by starmessage** [NuGet/docs.microsoft.com-nuget#1788] opened 2019-11-21 13:18 UTC
NuGet Warning NU1701
> Solution
> Change the project's target framework to one that the package supports.
> 

It is not clear what "target framework" I should put if the package contains a native DLL (developed in C/C++) and thus it supports all windows applications (no dependencies at all).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment] 2019-11-22 20:21
@rrelyea - can you please help with this?

**Comment by karann-msft** [comment] 2019-12-13 22:03
cc: @aortiz-msft

**Comment by karann-msft** [comment] 2020-01-15 20:11
Dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/238

**Closed by karann-msft** 2020-01-15 20:11 UTC
Labels: Team:Client, doc-question
