### ISSUE TITLE
Manage NuGet Packages View & Enable/Disable packages from the VS UI require some work

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#407] opened 2017-07-31 23:35 UTC
This issue was motivated by a feedback issue. 
https://developercommunity.visualstudio.com/content/problem/69961/manage-nuget-packages-for-solution-is-not-paying-a.html

For the user it wasn't clear that selecting the source from the dropdown list will only affect install/uninstall operations and not subsequent restore in the packages.config case. 

In addition we don't have documentation explaining that the behavior difference between packages.config and packagereference restore/install with regards to sources. 

I could not find any docs that clearly specify that. 
In addition, there's only documentation on how to disable soruces directly in the nuget.config, but none for vs.
https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

//cc @anangaur @kraigb 
@karann-msft

**Comment by StingyJack** [comment] 2017-09-27 00:05
As the user who opened that feedback - I can tell you that problem has nothing to do with restore operations. 
> visual studio is stuck and thinks it needs the LAN feed just to install something from nuget.org

I've opened another [issue for Nuget](https://developercommunity.visualstudio.com/content/problem/118566/vs-is-failing-to-install-a-nuget-package-from-nuge.html), and been told its is a duplicate of this, which might be true if this was for the problem I reported.

I cant install a package from Repo A because nuget vs UI requires Repo B to be online and available. The package being installed from Repo A has no knowledge of Repo B's existence, and any packages currently installed from Repo B can be queried for dependency issues. 

I'll take personal idiocy as the reason if i'm being daft here, but the reasons given for this active prevention seem suspect.

If you can figure out how to tag Rob Releya so he can see this, it would probably benefit both of us. I'd do it, but he has locked the post and I cant add a single comment to it.

**Comment by rrelyea** [comment] 2017-09-27 00:21
I am not trying to shut down the conversation. Thanks for writing back. I am surprised that DevCommunity items don't allow comment after they are closed.

Have you read the design for our improvements in this area that I pointed you towards: https://github.com/NuGet/Home/wiki/Package-Sources-Diagnostics

We'd love feedback about that.

NuGet is evolving away from PackagesConfig towards transitive NuGet systems (primarily PackageReference) where all sources are important, and that we shouldn't do an operation if one or more of them is offline. Doing anything else may lead to inconsistency that would also cause headaches.

We understand that there are many scenarios where users need to be offline from one or more sources, and it is annoying that we don't adapt well. That is why we've started designing how to improve with Package Source Diagnostics.

Look forward to more feedback about your NuGet experience.
Thanks, Rob 
Engineering Manager, NuGet Client Team

**Comment by StingyJack** [comment] 2017-09-27 04:33
The plan sounds like it could add complexity and none of the things listed are problems I have or have seen/heard.

- Package Source response times - never been a problem with Nuget.org or our private repo (except when we had a fire in the server room.) 
- Sources are behind a firewall - why is this a problem? 
- User is offline == User has no internet connection || user has no network connection ?  Visual Studio cant handle switching properly, so it makes no difference if nuget in VS works better or not in this respect.
- backing file shares are not my problem with running a private repo, unless you start requiring some uber-mega fibre-channel san. If thats the case, I'm going back to checking in copies of reference dll's.

Nuget (for the package consumer) is generally pain free and easily adaptable to.  Except...
- Searching is weird - sometimes the selected source works as a filter, and sometimes not.
- I can spend too long looking for a specific MSFT package because the namespaces or types aren't all searchable. R# helps some but its 50/50.
- The UI doesnt sort by any consistent way, is it alphabetical or by popularity or relevance? I cant tell. 
- The individual panels dont resize nicely and package information takes up too much space compared to project selection. Most solutions I use are > 40 projects, crammed in that little window.


Its a different story for an author with so many seemingly glaring but unfixed gaps and broken or inconsistent behaviors. 
 - still no SSDT project support. I have to hack it in as a lib\netframework11 and have an install powershell script try to attach the db ref
- dependencies have to be manually maintained in the nuspec.  So much other manual effort in team builds, etc for .net framework projects (no plans on even considering moving to Core until after it had DataSets and less bugs).. 
- I make symbols packages but cant upload them to a package source or they replace the non-symbols packages. 
- the examples on nuget.org are hello -world level. Its sometimes a few hours of fooling around to find out how to do something simple.
- There's a few others, but its late and im tired. 

Of all the things that need fixing, this issue isnt anywhere near the top of the list. I can uncheck a box in the package sources and get by. This issue is logged because I shouldn't have to, and because the reason given is still suspect.

>primarily PackageReference
With how bad VS 2017 has been, and how package references in the proj file automatically broke my stuff and delayed time critical projects, I dont wanna jump on the package reference bandwagon.

> This UI will have single disable for duration command, disable for all time command
If this is another yellow banner that pops up constantly and needlessly like the dependency validation or lightweight solution load, or the performance warnings for source control explorer (or the predecessors "learn to test" or "see our new build system") nags, please just dont. 

Sorry for all the salt. I'd have significantly less if not for that DevCommunity site. I was a real fan of MSFT  for 20+ years before coming across that thing..

**Comment by StingyJack** [comment] 2017-11-02 15:04
@rrelyea  ... also, why are there so many hoops when multi targeting? 

if should be as simple as 
`\lib\{runtime}\{targetFrameworkMoniker}`

... not "make additional special assemblies and a crazy powershell script". Especially when support for install.ps1 is getting the axe (another mistake in direction).

**Comment by nkolev92** [comment] 2017-11-03 04:04
@StingyJack 
Can you please clarify what do you mean by hoops when multi-targeting?

The current approach to multi-targetting is similar to what you're suggesting. 
```
lib\{framework name}[{version}]
```
From our [docs](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#framework-version-folder-structure). 

Thanks.

**Comment by StingyJack** [comment] 2017-11-03 12:43
Due to dependencies I cant change (Sap, Oracle, DacFx even) an assembly needs to be built for x86 and another for x64. Currently these must go in separate packages. 

There is a way to produce "reference assemblies" and do trickery with the install powershell, but it looks like a ridiculous amount of work for something that the foldering system should be able to accommodate easily.

**Comment by StingyJack** [comment] 2017-11-21 13:46
Back to the original point... if this package source is a filter, then it does not always work. I often have packages from non-selected repositories showing up in one of the lists (find, install, update)

**Comment by StingyJack** [comment] 2018-01-08 14:00
...in addition to the original rant, package reference still doesn't address the hint path problem.

**Comment by StingyJack** [comment] 2019-10-16 14:53
@stale - FOD

**Comment by JonDouglas** [comment] 2022-09-29 15:04
It is not immediately clear what the suggestion for this documentation enhancement/bug/addition would be. This issue has had no activity for many years and in the spirit of maintaining this repository, I'm going to close it until we can gain clarity.

There are new features such as package source mapping that can help give you the determinism sought through package sources and restore time.

But in general with all the wonderful feedback here already it sounds like perhaps it might be easier to absorb the feedback through a quick 30 minute call? Open invite to anyone viewing this issue who would like to give us feedback/suggestions:

aka.ms/talktonuget

**Closed by JonDouglas** 2022-09-29 15:04 UTC
Labels: doc-enhancement, P2, pinned

**Comment by StingyJack** [comment] 2022-10-03 20:51
@JonDouglas its not a suggestion for documentation.  It never was. I opened this as a program problem on developer community and it got moved here.
