### ISSUE TITLE
How to sort searched packages?

### ISSUE THREAD

**Issue by tb-mtg** [NuGet/docs.microsoft.com-nuget#1188] opened 2018-11-28 22:42 UTC
After performing a search is it possible to sort packages by not just relevance, but by any of the details provided (date last updated, total downloads, developer, version, etc...)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ad41c6-6549-e33b-407e-52357146f49a
* Version Independent ID: 741c3f86-a7c6-f48f-bc29-e49a439f7c61
* Content: [Finding and Choosing NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages)
* Content Source: [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Finding-and-Choosing-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment] 2018-11-29 10:32
Dupe of https://github.com/NuGet/Home/issues/7558

**Closed by karann-msft** 2018-11-29 10:32 UTC
