### ISSUE TITLE
dependencies -> 'groups' -> 'targetFramework' description is false

### ISSUE THREAD

**Issue by TiltonJH** [NuGet/docs.microsoft.com-nuget#1871] opened 2020-02-03 20:28 UTC
[Dependency groups](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependency-groups) states that the `groups` tag needs the `targetFramework` attribute and valid values can be found here: [Target Frameworks](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks).

Well no, they can't. [Target Frameworks](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks) does not list any of the valid values for `targetFramework` attribute. Using `net40`  for example failed. Therefore the provided example is also false.

[NU5128](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128) shows an correct example. But it doesn't give a list of valid values either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependency-groups)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by kartheekp-ms** [comment] 2020-03-02 20:11
Reopening this issue to fix the examples in the doc.

**Comment by kartheekp-ms** [comment] 2020-06-07 14:40
> [Target Frameworks](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks) does not list any of the valid values for `targetFramework` attribute. Using `net40`  for example failed.

@TiltonJH - I am unable to reproduce the failure when `net40` is used as `targetFramework` in `dependencies -> group` section of `.nuspec` file. It is possible that I may have missed one of the scenarios where we can reproduce the failure. If you are encountering any failures during `pack` then please create a new issue [here](https://github.com/NuGet/Home/issues/new). 

I have updated the `example` and added a `note` in the [`doc`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependency-groups). All the supported target frameworks are listed [here](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#supported-frameworks). 

> [NU5128](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128) shows an correct example. But it doesn't give a list of valid values either.

As per doc and my understanding `NU5128` displays list of valid `TFMs` for a specific `.nuspec` file only when `target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches`. Please free to create an issue [here](https://github.com/NuGet/Home/issues/new), if the error message doesn't provide required information.

We have identified an area of improvement in the doc and created another tracking [issue](NuGet/docs.microsoft.com-nuget#2061).

**Comment by TiltonJH** [comment] 2020-06-17 11:39
@kartheekp-ms How did you try to reproduce the failure? I used any version of `nuget.exe`.

Furthermore the example of [doc](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependency-groups) shows `.NETFramework4.7.2` as valid and not `net472`. The same is true for the example in [NU5128](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128)

**Comment by TiltonJH** [comment] 2020-06-17 11:54
@kartheekp-ms  In #1929 you mention `canonical` names. `.NETFramework4.7.2` is the canonical name of `net472`? If so where can one find a list of all `canonical` names?

**Comment by kartheekp-ms** [comment] 2020-06-17 17:44
> @kartheekp-ms How did you try to reproduce the failure? I used any version of `nuget.exe`.

@TiltonJH - I tried to reproduce by generating `NuGet package` from `.nuspec` file using `NuGet.exe version: 5.7`. Unable to reproduce the failure. Please create an [issue](https://github.com/NuGet/Home/issues/new) here with required information and it will be very helpful if you can zip a sample project and paste into this issue!
 
> Furthermore the example of [doc](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependency-groups) shows `.NETFramework4.7.2` as valid and not `net472`. The same is true for the example in [NU5128](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128)

`net472` is short target framework moniker or TFM for `.NETFramework4.7.2` as mentioned [here](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#supported-frameworks). The format of `Target Framework Moniker (TFM)` used in `lib/ref` folder is different when compared to the `TFM` used in dependency groups. For e.g. As per my current understanding unless proven wrong based on the `pack` failure you mentioned above, under `dependencies -> groups -> targetFramework` can be either `net472` or `.NETFramework4.7.2` where as under [`lib/ref`](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory) files only short target framework moniker or TFM is accepted (`net472` in this case). 

> @kartheekp-ms Kartheek Penagamuri FTE In #1929 you mention `canonical` names. Is `.NETFramework4.7.2` the canonical name of `net472`? If so where can one find a list of all `canonical` names?

canonical or official name for `.NETFramework4.7.2` is `.NETFramework,Version=4.7.2`. We have identified an area of improvement in the doc and created another [tracking issue](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2061).

**Comment by zivkan** [comment] 2020-06-17 19:09
> @TiltonJH - I tried to reproduce by generating `NuGet package` from `.nuspec` file using `NuGet.exe version: 5.7`. Unable to reproduce the failure. Please create an [issue](https://github.com/NuGet/Home/issues/new) here with required information and it will be very helpful if you can zip a sample project and paste into this issue!

To add a point of clarification, I also tried to reproduce the issue.

I used `nuget.exe spec` to create a `.nuspec` file, and changed the default dependency group to `net472`. When I packed and looked at the embedded nuspec, NuGet had re-written it to `.NETFramework4.7.2`.

So, it apepars to me that as long as your use `nuget.exe` to pack a nuspec, it's acceptable to use short folder names (`net472`) in the nuspec.  However, if you're using other tooling, for example creating a zip file with extension `.nupkg`, then using `n472` or other short names may not work.

I didn't test what happens when the `nupkg`'s `nuspec` file contains short folder names. I only tested what happens when you try to pack a `nuspec` that uses that format.

**Comment by TiltonJH** [comment] 2020-06-29 07:42
It seem to me that I have to retry this with `NuGet.exe version: 5.7`, In the mean time a switched to SDK type project and moved away from nuspec. Which solved this issue for my affected projects.

**Comment by kartheekp-ms** [comment] 2020-06-30 01:38
> It seem to me that I have to retry this with `NuGet.exe version: 5.7`

@TiltonJH - Additional details such as the `pack` error message and `NuGet.exe` version used would have helped us to provide guidance on which version of `NuGet.exe` fixed this issue.

> In the mean time a switched to SDK type project and moved away from nuspec. Which solved this issue for my affected projects.

Closing this issue as per above comment.

**Closed by kartheekp-ms** 2020-06-30 01:38 UTC
Labels: doc-bug, docsDay
