### ISSUE TITLE
What about GeneratePackageOnBuild?

### ISSUE THREAD

**Issue by ohadschn** [NuGet/docs.microsoft.com-nuget#1097] opened 2018-10-16 17:23 UTC
This looks like a good place to document it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by chuanboz** [comment] 2018-10-24 01:10
I'd be interested for this as well, GeneratePackageOnBuild is so convenience but no formal document on that.

**Comment by karann-msft** [comment] 2018-11-29 10:49
dupe of https://github.com/dotnet/docs/issues/7101

**Closed by karann-msft** 2018-11-29 10:49 UTC
Labels: Client

**Comment by gewarren** [comment] 2021-01-11 23:34
Can you please reopen this issue to track the work? The issue it was marked a duplicate of was closed because that article has been removed from dotnet/docs repo.

**Comment by zivkan** [comment] 2021-03-06 16:23
There's docs on it here: 
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#automatically-generate-package-on-build
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli#automatically-generate-package-on-build
