### ISSUE TITLE
Usage of contentFiles section

### ISSUE THREAD

**Issue by CeciAc** [NuGet/docs.microsoft.com-nuget#1351] opened 2019-03-18 13:19 UTC
@pgrawehr commented on [Mon Mar 18 2019](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/13)

This should have a full example on the usage of the <contentFiles/> section. With the snippet given, it lacks the relevant information that the <contentFiles/> section must be placed under the <metadata /> section, not besides the <files/> section (at the root level). 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [NUSPEC-Dateireferenz für NuGet](https://docs.microsoft.com/de-de/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment] 2019-03-18 13:20
Hi team, 
I'm moving this here since the user is making a suggestion on the documentation
best

**Comment by pgrawehr** [comment] 2019-03-19 15:56
> 
> 
> @pgrawehr commented on [Mon Mar 18 2019](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/13)
> 
> This should have a full example on the usage of the section. With the snippet given, it lacks the relevant information that the section must be placed under the section, not besides the section (at the root level).
> #### Dokumentdetails
> 
> ⚠ _Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich._
> 
>     * ID: 06a19d7d-253d-f17f-6421-624c9867473d
> 
>     * Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
> 
>     * Content: [NUSPEC-Dateireferenz für NuGet](https://docs.microsoft.com/de-de/nuget/reference/nuspec#feedback)
> 
>     * Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/nuspec.md)
> 
>     * Product: **nuget**
> 
>     * GitHub Login: @karann-msft
> 
>     * Microsoft Alias: **karann**

Sorry, the content of the post was messed up a bit. This should have read: 

This should have a full example on the usage of the section "contentFiles". With the snippet given, it lacks the relevant information that the section "contentFiles" must be placed under the section "metadata", not besides the section "files" (at the root level).

**Comment by karann-msft** [comment] 2020-02-25 22:34
dupe of #775

**Closed by karann-msft** 2020-02-25 22:34 UTC
Labels: doc-enhancement
