### ISSUE TITLE
Command to clear package cache is missing nuget option for dotnet

### ISSUE THREAD

**Issue by DiscoPYF** [NuGet/docs.microsoft.com-nuget#2080] opened 2020-06-25 14:06 UTC
In the section "Other potential conditions", the command to clear the package cache with the `dotnet` command line tool is written as: `dotnet locals all --clear` but it should be `dotnet nuget locals all --clear`, as documented in https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

![image](https://user-images.githubusercontent.com/8124146/85734969-50610600-b6f5-11ea-9d6f-902c8aa4b3bd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment] 2020-06-25 19:10
closing as duplicate of #2055

**Closed by zivkan** 2020-06-25 19:10 UTC
