### ISSUE TITLE
NuGet Warning NU5048 - Icon URL is deprecated

### ISSUE THREAD

**Issue by c0g1t8** [NuGet/docs.microsoft.com-nuget#1965] opened 2020-03-22 16:30 UTC
I suggest we update the screenshot above or add a note explaining the discrepancy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard NuGet package - Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli#feedback)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment] 2022-01-31 16:35
Closing this issue as it's largely a dupe of other issue referenced here.

**Closed by JonDouglas** 2022-01-31 16:35 UTC
Labels: doc-bug
