### ISSUE TITLE
issue https://github.com/NuGet/docs.microsoft.com-nuget/issues/1419 does not show up  in this list

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1741] opened 2019-10-16 14:38 UTC
Its not in either the closed or open lists, but shows up in github's list and is linked to this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a154e5f-436d-6297-ec05-4d134a2404f9
* Version Independent ID: 1c782e82-db9a-bf77-05ef-cd49374aee36
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)
* Content Source: [docs/consume-packages/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment] 2019-10-16 18:23
how do you mean? I searched for it and was able to find it:
![image](https://user-images.githubusercontent.com/16904420/66947257-6d422700-f007-11e9-9e28-cab63afd95e9.png)

**Comment by karann-msft** [comment] 2019-12-13 22:09
@StingyJack - sorry but we haven't been able to find the root cause for this :( 
If you'd like, feel free to file an issue similar to #1419 or edit this one to treat as a pointer to it.

**Comment by Mikejo5000** [comment] 2019-12-13 23:26
Fixed and closing. Because the topic was moved, the embedded metadata referring to the topic was out of date (you'd think that would be handled automatically...). I pasted in the topic metadata from this issue into #1419. (To get the metadata, click "..." > Edit above. Same process to paste in the metadata.)

**Closed by Mikejo5000** 2019-12-13 23:26 UTC
Labels: external
