### ISSUE TITLE
Setting Key Case Sensitivity

### ISSUE THREAD

**Issue by nicholjy** [NuGet/docs.microsoft.com-nuget#1301] opened 2019-02-06 21:50 UTC
The second paragraph of https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file states that setting names are case insensitive.  This document, however, states that the keys are case sensitive.  Are these statements referring to the same data (keys vs names)?  If so, which is correct (case sensitive or insensitive)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment] 2019-08-08 19:38
Might be a duplicate of #1477

**Comment by karann-msft** [comment] 2020-02-11 23:13
Closing as dupe of #1477

**Closed by karann-msft** 2020-02-11 23:13 UTC
Labels: duplicate
