### ISSUE TITLE
Unable to retrieve information about package - The content at '<link>' is not a valid JSON object.

### ISSUE THREAD

**Issue by Mastahiro** [NuGet/docs.microsoft.com-nuget#2768] opened 2022-06-01 09:20 UTC
While trying to build IoTEdge modules for my project, I come across the following error:

```
#18 3.610 /usr/share/dotnet/sdk/3.1.419/NuGet.targets(128,5): error : Failed to retrieve information about 'Microsoft.Extensions.DependencyInjection.Abstractions' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json'. [/src/projectname/projectname.csproj]
#18 3.610 /usr/share/dotnet/sdk/3.1.419/NuGet.targets(128,5): error :   The content at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json' is not a valid JSON object. [/src/projectname/projectname.csproj]
#18 3.610 /usr/share/dotnet/sdk/3.1.419/NuGet.targets(128,5): error :   The JSON document is not an object. [/src/projectname/projectname.csproj]
```

Navigating to [index.json](https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json) it loads and contains the following:
```
{
  "versions": [
    "1.0.0-rc1-final",
    "1.0.0-rc2-final",
    "1.0.0",
    "1.0.1",
    "1.0.2",
    "1.1.0-preview1-final",
    "1.1.0",
    "1.1.1",
    "2.0.0-preview1-final",
    "2.0.0-preview2-final",
    "2.0.0",
    "2.1.0-preview1-final",
    "2.1.0-preview2-final",
    "2.1.0-rc1-final",
    "2.1.0",
    "2.1.1",
    "2.2.0-preview1-35029",
    "2.2.0-preview2-35157",
    "2.2.0-preview3-35497",
    "2.2.0",
    "3.0.0-preview.18572.1",
    "3.0.0-preview.19074.2",
    "3.0.0-preview3.19153.1",
    "3.0.0-preview4.19216.2",
    "3.0.0-preview5.19227.9",
    "3.0.0-preview6.19304.6",
    "3.0.0-preview7.19362.4",
    "3.0.0-preview8.19405.4",
    "3.0.0-preview9.19423.4",
    "3.0.0-rc1.19456.10",
    "3.0.0",
    "3.0.1",
    "3.0.2",
    "3.0.3",
    "3.1.0-preview1.19506.1",
    "3.1.0-preview2.19525.4",
    "3.1.0-preview3.19553.2",
    "3.1.0",
    "3.1.1",
    "3.1.2",
    "3.1.3",
    "3.1.4",
    "3.1.5",
    "3.1.6",
    "3.1.7",
    "3.1.8",
    "3.1.9",
    "3.1.10",
    "3.1.11",
    "3.1.12",
    "3.1.13",
    "3.1.14",
    "3.1.15",
    "3.1.16",
    "3.1.17",
    "3.1.18",
    "3.1.19",
    "3.1.20",
    "3.1.21",
    "3.1.22",
    "3.1.23",
    "3.1.24",
    "3.1.25",
    "5.0.0-preview.1.20120.4",
    "5.0.0-preview.2.20160.3",
    "5.0.0-preview.3.20215.2",
    "5.0.0-preview.4.20251.6",
    "5.0.0-preview.5.20278.1",
    "5.0.0-preview.6.20305.6",
    "5.0.0-preview.7.20364.11",
    "5.0.0-preview.8.20407.11",
    "5.0.0-rc.1.20451.14",
    "5.0.0-rc.2.20475.5",
    "5.0.0",
    "6.0.0-preview.1.21102.12",
    "6.0.0-preview.2.21154.6",
    "6.0.0-preview.3.21201.4",
    "6.0.0-preview.4.21253.7",
    "6.0.0-preview.5.21301.5",
    "6.0.0-preview.6.21352.12",
    "6.0.0-preview.7.21377.19",
    "6.0.0-rc.1.21451.13",
    "6.0.0-rc.2.21480.5",
    "6.0.0",
    "6.0.2-mauipre.1.22054.8",
    "6.0.2-mauipre.1.22102.15",
    "7.0.0-preview.1.22076.8",
    "7.0.0-preview.2.22152.2",
    "7.0.0-preview.3.22175.4",
    "7.0.0-preview.4.22229.4"
  ]
}
```

I've tried clearing cache, [changing protocolVersion to 2](https://stackoverflow.com/questions/71330113/nuget-package-manager-is-not-a-valid-json-object), [removing and re-adding nuget.org](https://stackoverflow.com/questions/69280391/nuget-not-installing-packages), building on a different machine, and on old release versions that worked. This error only started happening for the last couple days.

I'm unsure if this is a NuGet or package related issue so any insight or pointers would be helpful.

**Comment by s4kas** [comment] 2022-06-01 16:16
Had the same problem the 31/05 and the 01/06 in the morning.
Magically it started working again the 01/06 in the afternoon. 
What happened?

**Comment by Mastahiro** [comment] 2022-06-01 16:27
As pointed out, the issue is now technically fixed, but some clarification would still be greatly appreciated.

**Comment by joelverhagen** [comment] 2022-06-14 19:32
Hello, thanks you for taking the time to report this. This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/9140. We'll use that one issue to track the api.nuget.org connectivity problem as well as the JSON corruption issue.

As of now, we have performed a failover for our CDN provider which we expect to mitigate the problem. If you are still facing a problem, please post on the issue I linked above.

**Closed by joelverhagen** 2022-06-14 19:32 UTC
