### ISSUE TITLE
supported frameworks

### ISSUE THREAD

**Issue by collenbrecht** [NuGet/docs.microsoft.com-nuget#1026] opened 2018-08-21 06:50 UTC
the .net frameworks are missing the newest ones. can someone add them please?
net47 and net471 I think. thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#supported-frameworks)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by collenbrecht** [comment] 2018-08-21 06:51
I see that Brett already opened the same issue. this one can be closed.

**Comment by karann-msft** [comment] 2018-08-21 18:48
Closing as dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/940

**Closed by karann-msft** 2018-08-21 18:48 UTC
