### ISSUE TITLE
The NuGet package could not be restored

### ISSUE THREAD

**Issue by chenzheng1988** [NuGet/docs.microsoft.com-nuget#1237] opened 2018-12-21 09:40 UTC
The NuGet package could not be restored.
VS2017
screenshot as follows:
![image](https://user-images.githubusercontent.com/38801660/50335820-6feb0180-0547-11e9-9330-be8a9fc069ed.png)

**Comment by zivkan** [comment] 2018-12-27 21:06
dupe of NuGet/Home#3324

**Closed by zivkan** 2018-12-27 21:06 UTC
Labels: ClosedAs:NotDocs, Team:Client
