### ISSUE TITLE
Describe AssetTargetFallback

### ISSUE THREAD

**Issue by guardrex** [NuGet/docs.microsoft.com-nuget#410] opened 2017-08-02 15:32 UTC
We were discussing `PackageTargetFallback` (see: https://github.com/dotnet/cli/issues/3439#issuecomment-319702662), and there doesn't seem to be an issue to cover updating the [Wiki here](https://github.com/NuGet/Home/wiki/PackageTargetFallback-(new-design-for-Imports)) or the [OPS topic here](https://docs.microsoft.com/nuget/schema/msbuild-targets#packagetargetfallback) to surface `AssetTargetFallback`. Please close this if the topic updates are already handled.

**Comment by CamSoper** [comment] 2018-08-28 23:17
Dupe of #511

**Closed by CamSoper** 2018-08-28 23:17 UTC
Labels: P3, duplicate
