### ISSUE TITLE
Not enough information to be useful

### ISSUE THREAD

**Issue by TheRealZonaP** [NuGet/docs.microsoft.com-nuget#1774] opened 2019-11-09 20:58 UTC
This page is not useful.  Please see https://digitalhouseblog.wordpress.com/2019/08/22/how-to-make-a-nuget-package-for-c/ for an example of the information needed to actually create a native NuGet package by hand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7064d86-7de7-1a58-393b-39a5281a9617
* Version Independent ID: 8efa557b-8b1e-6320-4640-5226b8983832
* Content: [Creating Native NuGet Packages](https://docs.microsoft.com/en-us/nuget/guides/native-packages)
* Content Source: [docs/guides/Native-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Native-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment] 2019-11-12 19:00
Like I call out in a dupe of this issue, NuGet does not have a first-class experience for creating native packages. Take a look at [vcpkg](https://github.com/Microsoft/vcpkg) which might be what you are looking for.

**Comment by karann-msft** [comment] 2019-12-04 22:36
@rrelyea - can you help better document the NuGet story around native packages :)

**Comment by karann-msft** [comment] 2020-02-08 00:19
We are rolling up all native and C++ related issues into #238 .

**Closed by karann-msft** 2020-02-08 00:19 UTC
Labels: doc-enhancement
