### ISSUE TITLE
nuget.config Environmental variable usage is contradictory

### ISSUE THREAD

**Issue by NickCraver** [NuGet/docs.microsoft.com-nuget#2062] opened 2020-06-08 22:53 UTC
In the docs, we have the textual documentation:
> Note that you have to use Windows-style environment variables (starts and ends with %) even on Mac/Linux. Having `$HOME/NuGetRepository` in a configuration file will not resolve. On Mac/Linux the value of `%HOME%\NuGetRepository` will resolve to `/home/myStuff/NuGetRepository`.

But in the actual example code:
```xml
        <!--
            ...
            In this example, %PACKAGEHOME% is an environment variable. On Mac/Linux,
            use $PACKAGE_HOME/External as the value.
        -->
        <add key="repositoryPath" value="%PACKAGEHOME%\External" />
```

So the docs say use Windows-style variables (which [is what actually works according to others](https://twitter.com/jeff_papp/status/1270121673325330432)), but the example says the opposite. Am I reading this wrong, or should we adjust the example comment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment] 2020-08-13 19:47
Dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/1959

**Closed by JonDouglas** 2020-08-13 19:47 UTC
Labels: doc-bug
