### ISSUE TITLE
Can't restore NuGets - NuGet packages missing. Can't find the nuget...targets file

### ISSUE THREAD

**Issue by rahg-bmake** [NuGet/docs.microsoft.com-nuget#2045] opened 2020-05-20 13:49 UTC
A working hack is listed here:
https://github.com/Azure-Samples/active-directory-dotnet-graphapi-console/issues/43

Please refer to the same for the issue.

For me, the problem occured when checking in a new project which depended on Azure.Cosmos nuget 3.9.0.

**Comment by zivkan** [comment] 2020-05-20 14:05
NuGet hasn't created and added the `$(SolutionDir)/.nuget/` files since Visual Studio 2013, and even then only when the developer right clicks the solution in Solution Explorer and selects a certain menu item.

To me, this suggests it's an old project that was possibly copied to a new solution/repository, without with dependent files. In any case, I think we need more details on how to reproduce the problem.

**Comment by rahg-bmake** [comment] 2020-05-20 15:28
So, it was a new project on .net framework 4.7 which was then imported in a relatively older project using import project option. I also moved the new project within the solution explorer to a different folder.

**Comment by zivkan** [comment] 2020-05-22 04:06
Are you trying to get the NuGet team's attention on the Azure-Samples issue, or are you trying to say that your own project had a similar error, and you found the advice in that issue helped you?

You don't appear to be asking for help, which makes me think you're asking for a change the product. But, I don't know how to reproduce the problem you're describing, so I don't know what you're asking to be changed.

Can you please provide reproduction steps, that someone on a new computer can follow to experience the problem you're reporting?

**Comment by rahg-bmake** [comment] 2020-05-22 20:17
I just meant to say that my own project had a similar error, and I found the advice in that issue helped me. As for reproducibility, I will have to check again the simplest steps which lead to the erroneous csproj. I am relatively new to c#, so I certainly don't understand many aspects on it. I can work on creating a reproducible project later.

Essentially this is a scenario in which nugets restore from Visual studio 2019 doesn't work.

**Comment by zivkan** [comment] 2020-06-14 14:36
CLosing as we're unable to proceed without a reproduction.

**Closed by zivkan** 2020-06-14 14:36 UTC
