### ISSUE TITLE
Is there some API I could get my api keys and refresh my api key?

### ISSUE THREAD

**Issue by WeihanLi** [NuGet/docs.microsoft.com-nuget#2703] opened 2022-03-28 16:37 UTC
Hi, I'm using the api key in the Azure DevOps Pipeline, I had to update the api key manually when the api key expired.

Is there an API to refresh the api key expiry or API to refresh the api key? If so maybe I could renew the api key automatically before it's expired

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94d077e7-a1d6-1551-b6f1-04e1ecd98f32
* Version Independent ID: 9fffab6a-ede7-4305-04aa-18c9db3ac9c2
* Content: [Scoped API keys](https://docs.microsoft.com/en-us/nuget/nuget-org/scoped-api-keys)
* Content Source: [docs/nuget-org/scoped-api-keys.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/nuget-org/scoped-api-keys.md)
* Product: **nuget**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by joelverhagen** [comment] 2022-12-21 17:25
Apologies on the delay.

This is not possible today. By design, updating the API key is a manual thing that requires a 2FA-protected, Microsoft account or Azure Active Directory account sign in session. 

We've talked about a new approach with OpenID Connect and pushing from GitHub Actions without the need for an API key, but it's very much in the proposal phase. 

I'm going to close this issue in like of https://github.com/NuGet/NuGetGallery/issues/9332. Feel free to open a feature request on https://github.com/NuGet/NuGetGallery/issues if you believe a totally different option is needed. There are big security questions for the idea you have here so those would need to be explored as well.

**Closed by joelverhagen** 2022-12-21 17:25 UTC
