### ISSUE TITLE
Unknown Command "POST"

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/docs.microsoft.com-nuget#1245] opened 2019-01-02 04:54 UTC
Hi Everyone,

The POST command is not working fine as you mentioned in the help link. I have used the command like below, But I have faced the below issue. 

**Command:**

nuget.exe POST https://www.nuget.org
/api/v2/package/{ID}/{Version} X-NuGet-ApiKey: {KEY}

**Issue:**

![image](https://user-images.githubusercontent.com/16695209/50580734-726b2680-0e78-11e9-8acb-0a0d480e8662.png)

Could you please check this and provide the solution to relist the NuGet packages in nuget.org.?

Thanks,
Ganesan R.

**Comment by Mikejo5000** [comment] 2019-08-08 21:21
Looks like a duplicate of #1246

**Comment by Mikejo5000** [comment] 2019-08-08 21:21
Closing in favor of the other issue

**Closed by Mikejo5000** 2019-08-08 21:21 UTC
Labels: duplicate
