### ISSUE TITLE
Add wildcard examples

### ISSUE THREAD

**Issue by zapr-16** [NuGet/docs.microsoft.com-nuget#1535] opened 2019-07-15 16:26 UTC
Wildcard examples are not very useful. I have tried *.nuspec and get the error "illegal characters in path". I've been trying many wildcard filters for half an hour and still no luck

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e18eb26-7a73-5e48-abd0-3d53476c6f91
* Version Independent ID: 5469de95-4b00-2fbd-f3c0-1cde036f3c7f
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack#feedback)
* Content Source: [docs/tools/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by anangaur** [comment] 2019-12-06 22:23
@chgill-MSFT , Can you try the example and see if this is a product bug? Ideally whatever documented should have worked and may be we regressed?

**Comment by karann-msft** [comment] 2020-02-25 18:39
Dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/1861

**Closed by karann-msft** 2020-02-25 18:39 UTC
Labels: doc-bug
