### ISSUE TITLE
Nuget packages do not get restored properly

### ISSUE THREAD

**Issue by Jiyuu** [NuGet/docs.microsoft.com-nuget#1466] opened 2019-06-09 01:40 UTC
Attempting to build the project at https://github.com/AnkiTools/AnkiSharp/commit/e37f513421d18e356dc439ef0d56cfe61704f55a (linking to the specific commit i tried to avoid complications) fails giving the standard error about needing a nuget restore.
unfortunately using both vs2017 and 2019 non of the restore options properly restore the nuget packages into the expected location and the build continues to fail.

**Comment by Jiyuu** [comment] 2019-06-09 02:03
Looking a bit more into the issue i am starting to suspect at least part of the issue is that the files in that project have a utf8 BOM in them, removing the BOM seems to get VS to at least parse the packages used in the project, instead of showing a default list.
But doing that alone doesnt seem to enable the restore yet.

**Comment by Jiyuu** [comment] 2019-06-09 02:24
and finally i managed to figure it out, the BOM doesnt seem to have had anything to do with it, and i am not sure if this is considered an issue by Nuget.

The cause of the issue seems to be the inclusion of both the following section in the csproj file
```
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-*" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>11.0.2</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.5.231</Version>
    </PackageReference>
  </ItemGroup>
```

as well as having most of the actual dependencies in a packages.config file.
i assume these are two approaches for handling nuget and having this section in the config made it ignore the packages.config file.

As a user i would have preferred VS or nuget to raise a warning that such a conflict exists, but would understand if this is considered out of scope.

**Comment by zivkan** [comment] 2019-06-11 17:32
Closing as duplicate of NuGet/Home#7270

**Closed by zivkan** 2019-06-11 17:32 UTC
