### ISSUE TITLE
Document how to suppress multiple warnings

### ISSUE THREAD

**Issue by john-mills-nz** [NuGet/docs.microsoft.com-nuget#1948] opened 2020-03-11 22:27 UTC
Please update this documentation to include how to suppress multiple warnings - https://github.com/dotnet/sdk/issues/8792#issuecomment-393756980.

Windows:
-p:NoWarn=\"NUXXXX;NUXXXX\"

Linux:
-p:NoWarn='"NUXXXX;NUXXXX"'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d85bd49a-f83d-7588-5c70-edad5270c0f0
* Version Independent ID: 11cc9edc-4803-c768-5cdd-25c9b41ec8d3
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-pack#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Piedone** [comment] 2021-02-06 23:28
Would this be the same for `dotnet build` and `nuget.exe pack` (since this issue refers to the NuGet docs)? If yes, what would be the correct/recommended syntax when using `dotnet build` and NOT `dotnet msbuild`? While [the docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nowarn-compiler-option) suggest that something like `dotnet build -nowarn:AD0001,MSB3026` should work, it doesn't and I still get these warnings.

All syntaxes that I tried and don't work (either doesn't have an effect and I still occasionally see the disabled warnings or cause an error), all as parameters to `dotnet build`:

- `/p:NoWarn=AD0001%2CMSB3026`
- `/nowarn:AD0001%2CMSB3026`
- `-noWarn:AD0001%2CMSB3026`
- `-nowarn:AD0001,MSB3026`
- `/p:NoWarn=\"AD0001;MSB3026\"` ("MSBUILD : error MSB1006: Property is not valid.") Tried on Windows. This is the one under the linked comment. `/p:NoWarn='"AD0001;MSB3026"'` doesn't work either ("Unexpected token '"AD0001;MSB3026"' in expression or statement.").
- `/p:NoWarn=AD0001%3BMSB3026`
- `-p:NoWarn="AD0001;MSB3026"` (as suggested in this issue, on Windows): "MSBUILD : error MSB1006: Property is not valid."

The only thing that does work is the following but do note that here we're using two parameters instead of one (my hunch is that something is off with the separator): `/p:NoWarn=AD0001 -warnAsMessage:MSB3026`.

Probably worth noting that this happens in a build in TeamCity but

**Comment by JonDouglas** [comment] 2022-01-31 16:28
We have both nuget pack & dotnet pack in which have different philosophies of CLI experiences. 

nuget CLI will allow one to specify a list of properties that will override values in the project file. You can read about those here: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties

Very similarly, the dotnet CLI allows the same or can even invoke `msbuild` itself.

For example of `NoWarn`:

> Suppresses the specified warnings. Only the numeric part of the warning identifier must be specified. Multiple warnings are separated by semicolons. This parameter corresponds to the /nowarn switch of the compilers.

Thus this issue doesn't seem like it belongs here. Although we can add more syntax here, the problem is about MSBuild properties and not NuGet ones. I'm going to close this for now since it's been awhile since last comments and there's not much action on our end here.

**Closed by JonDouglas** 2022-01-31 16:28 UTC
Labels: doc-enhancement
