### ISSUE TITLE
IsPackable property is not documented

### ISSUE THREAD

**Issue by drieseng** [NuGet/docs.microsoft.com-nuget#2901] opened 2022-09-28 11:51 UTC
The **IsPackable** property, which is linked to in the **Automatically generate package on build** section of this document, is not documented on the linked page.

Please document this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31da7408-981b-cc54-1791-ca39dbdbc091
* Version Independent ID: 2060c9e8-7f2e-5da1-ee19-d196f38339fe
* Content: [Create a NuGet package using MSBuild](https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild)
* Content Source: [docs/create-packages/creating-a-package-msbuild.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/creating-a-package-msbuild.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment] 2022-09-29 15:30
Duplicate of #2036

**Closed by JonDouglas** 2022-09-29 15:30 UTC
Labels: good first issue, hacktoberfest
