### ISSUE TITLE
Native framework

### ISSUE THREAD

**Issue by stephenatwork** [NuGet/docs.microsoft.com-nuget#1480] opened 2019-06-20 11:20 UTC
No mention of native framework on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#feedback)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by stephenatwork** [comment] 2019-10-16 09:38
Still an issue. Reopen please.

**Comment by karann-msft** [comment] 2020-01-15 20:17
Dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/238

**Closed by karann-msft** 2020-01-15 20:17 UTC
Labels: doc-enhancement
