### ISSUE TITLE
New Doc for Content / ContentFiles

### ISSUE THREAD

**Issue by karann-msft** [NuGet/docs.microsoft.com-nuget#507] opened 2017-10-12 19:56 UTC
We need a new doc based on this blog post - https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

The blog post has several things that are wrong with it.

**Comment by kraigb** [comment] 2018-03-08 18:31
Closing as dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/300.

**Closed** 2018-03-22 23:19 UTC
