### ISSUE TITLE
Why CLI

### ISSUE THREAD

**Issue by Korporal** [NuGet/docs.microsoft.com-nuget#1399] opened 2019-04-12 18:31 UTC
It's frankly ridiculous that Visual Studio provides zero support for the last publish step. Even after a decade of asking for this Microsoft has simply refused to do this. It is absurd.

**Comment by karann-msft** [comment] 2019-04-12 21:12
@Korporal - while we appreciate the feedback, creating multiple duplicate issues seldom help. 
Closing as duplicate of https://github.com/NuGet/docs.microsoft.com-nuget/issues/1389 which you created.

**Closed** 2019-04-12 21:16 UTC
Labels: ClosedAs:ProductFeedback, duplicate
